# Generated by Django 4.1.7 on 2023-04-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_question_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='owner',
            new_name='Customer_id',
        ),
    ]
