# Generated by Django 4.1.7 on 2023-04-03 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_customer_id_question_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='owner',
            new_name='customer_id',
        ),
    ]
