# Generated by Django 4.1.7 on 2023-04-03 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('base', '0006_rename_owner_survey_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
        ),
    ]
