# Generated by Django 4.2 on 2023-04-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_survey_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(null=True, upload_to='base/images'),
        ),
    ]
