# Generated by Django 4.2 on 2023-04-10 11:45

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(null=True, upload_to='base/images', validators=[base.validators.validate_file_size]),
        ),
    ]
